[package]
name = "external-secret-explain"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
dirs = "6.0.0"
k8s-openapi = { version = "0.24.0", features = ["latest"] }
kube = { version = "0.98.0", features = [
    "client",
    "runtime",
    "derive",
    "rustls-tls",
] }
kube-client = "0.98.0"
kube-derive = "0.98.0"
# oci-sdk = "0.3.0"
# oci-sdk = { path = "../oci-rust-sdk/" }
oci-sdk = { git = "https://github.com/wasilak/oci-rust-sdk.git" }
reqwest = "0.12.12"
schemars = "0.8.21"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
serde_yaml = "0.9.34"
tokio = { version = "1.43.0", features = ["full"] }
[dev-dependencies]
async-std = "1.13.0"
